### ISSUE TITLE
Add documentation to the repo.

### ISSUE THREAD

**Issue by jamie-lemon** [ArtifexSoftware/mupdf.js#7]
Currently much of our documentation exists within the main mupdf repo. We need to move this into this repo.

**Comment by ccxvii** [comment]
The API documentation in the main mupdf repo also applies to the java library and mutool run (all these three APIs are kept the same as far as possible). We can't move the docs here directly, because the main mupdf repo also needs it.

Let's look into a way to automatically sync the docs over here if we want a copy with this repo.

Manual syncing is not going to work in the long run, since I can promise you that we will end up forgetting to update the docs in one of the two locations if the syncing does not happen automatically.

**Comment by jamie-lemon** [comment]
Rethinking this - let's not move it - we can just keep the "core API" (namely what `mupdf.js` provides) documented as we have it in MuPDF documentation. Although we may need to amend it a little to connect it better with the "mupdf.js" product.

So ourdocumentation here will be at a higher API level, giving the user Getting Started & How to Guide with typical JavaScript libraries. I will reword this issue accordingly.

**Comment by jamie-lemon** [comment]
First phase complete for version 0.2.0 of mupdf.js, see: https://github.com/ArtifexSoftware/mupdf.js/pull/21
